"""LabLens AI - PDF Report Generation Service"""
import io
from typing import List, Dict, Any, Optional
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from app.core.logging import get_logger

logger = get_logger(__name__)


class PDFReportService:
    def generate_summary_pdf(
        self,
        report_data: Dict[str, Any],
        summary: Dict[str, Any],
        trend_data: Optional[List[Dict[str, Any]]] = None,
        output_path: Optional[str] = None,
    ) -> bytes:
        """Generate a professional PDF summary report."""

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2*cm,
            bottomMargin=2*cm,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=24,
            textColor=colors.HexColor("#1e40af"),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
        )

        heading2_style = ParagraphStyle(
            "CustomHeading2",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#1e40af"),
            spaceAfter=10,
            spaceBefore=15,
            fontName="Helvetica-Bold",
        )

        heading3_style = ParagraphStyle(
            "CustomHeading3",
            parent=styles["Heading3"],
            fontSize=12,
            textColor=colors.HexColor("#374151"),
            spaceAfter=8,
            spaceBefore=10,
            fontName="Helvetica-Bold",
        )

        normal_style = ParagraphStyle(
            "CustomNormal",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            alignment=TA_JUSTIFY,
        )

        warning_style = ParagraphStyle(
            "WarningStyle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#92400e"),
            backColor=colors.HexColor("#fef3c7"),
            borderPadding=8,
            leading=14,
        )

        critical_style = ParagraphStyle(
            "CriticalStyle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#991b1b"),
            backColor=colors.HexColor("#fee2e2"),
            borderPadding=8,
            leading=14,
        )

        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#6b7280"),
            leading=12,
            alignment=TA_JUSTIFY,
        )

        story = []

        # Header
        story.append(Paragraph("LabLens AI", title_style))
        story.append(Paragraph("Medical Report Analysis Summary", styles["Heading2"]))
        story.append(Spacer(1, 0.2*inch))

        # Patient Info
        patient = report_data.get("patient_info", {})
        if patient:
            info_data = []
            if patient.get("name"):
                info_data.append(["Patient Name:", patient["name"]])
            if report_data.get("report_date"):
                info_data.append(["Report Date:", str(report_data["report_date"])])
            if report_data.get("lab_name"):
                info_data.append(["Laboratory:", report_data["lab_name"]])
            if patient.get("age"):
                info_data.append(["Age:", str(patient["age"])])
            if patient.get("gender"):
                info_data.append(["Gender:", patient["gender"]])

            if info_data:
                info_table = Table(info_data, colWidths=[2*inch, 4*inch])
                info_table.setStyle(TableStyle([
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(info_table)
                story.append(Spacer(1, 0.2*inch))

        # Safety Disclaimer
        story.append(Paragraph(
            "<b>IMPORTANT:</b> This report is generated by an AI system for informational and educational purposes only. "
            "It does NOT constitute a medical diagnosis. Always consult a qualified healthcare professional for interpretation, "
            "diagnosis, and treatment decisions.",
            disclaimer_style
        ))
        story.append(Spacer(1, 0.2*inch))

        # Executive Summary
        story.append(Paragraph("Executive Summary", heading2_style))
        story.append(Paragraph(summary.get("overall_summary", "No summary available."), normal_style))
        story.append(Spacer(1, 0.15*inch))

        # High Priority Findings
        high_priority = summary.get("high_priority_findings", [])
        if high_priority:
            story.append(Paragraph("⚠ High Priority Findings", heading2_style))
            for finding in high_priority:
                story.append(Paragraph(f"• {finding}", critical_style))
            story.append(Spacer(1, 0.15*inch))

        # Attention Findings
        attention = summary.get("attention_findings", [])
        if attention:
            story.append(Paragraph("⚡ Findings Requiring Attention", heading2_style))
            for finding in attention:
                story.append(Paragraph(f"• {finding}", warning_style))
            story.append(Spacer(1, 0.15*inch))

        # Normal Findings
        normal = summary.get("normal_findings", [])
        if normal:
            story.append(Paragraph("✓ Normal Findings", heading2_style))
            for finding in normal:
                story.append(Paragraph(f"• {finding}", normal_style))
            story.append(Spacer(1, 0.15*inch))

        # Detailed Results Table
        story.append(PageBreak())
        story.append(Paragraph("Detailed Test Results", heading2_style))

        results = report_data.get("test_results", [])
        if results:
            table_data = [["Test Name", "Result", "Unit", "Reference Range", "Status"]]

            for r in results:
                status = r.get("status", "unknown")
                status_color = {
                    "normal": colors.green,
                    "borderline": colors.orange,
                    "low": colors.orange,
                    "high": colors.orange,
                    "critically_low": colors.red,
                    "critically_high": colors.red,
                }.get(status, colors.grey)

                table_data.append([
                    r.get("test_name", ""),
                    str(r.get("result") or r.get("result_text", "N/A")),
                    r.get("unit", ""),
                    r.get("reference_text", "N/A"),
                    Paragraph(f"<font color='{status_color.hexval()}'>{status.replace('_', ' ').title()}</font>", normal_style),
                ])

            results_table = Table(table_data, colWidths=[2.2*inch, 1*inch, 0.8*inch, 1.5*inch, 1*inch])
            results_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("FONTSIZE", (0, 1), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
                ("TOPPADDING", (0, 1), (-1, -1), 6),
            ]))
            story.append(results_table)

        # Parameter Explanations
        explanations = summary.get("parameter_explanations", [])
        if explanations:
            story.append(Spacer(1, 0.2*inch))
            story.append(Paragraph("Parameter Explanations", heading2_style))
            for exp in explanations:
                story.append(Paragraph(f"<b>{exp.get('test_name', '')}:</b> {exp.get('explanation', '')}", normal_style))
                story.append(Spacer(1, 0.05*inch))

        # Doctor Discussion Questions
        questions = summary.get("doctor_questions", [])
        if questions:
            story.append(Spacer(1, 0.2*inch))
            story.append(Paragraph("Questions for Your Doctor", heading2_style))
            for q in questions:
                story.append(Paragraph(f"• {q}", normal_style))

        # Health Education
        education = summary.get("health_education", [])
        if education:
            story.append(Spacer(1, 0.2*inch))
            story.append(Paragraph("Health Education", heading2_style))
            for edu in education:
                story.append(Paragraph(f"• {edu}", normal_style))

        # Data Quality Warnings
        warnings = summary.get("data_quality_warnings", [])
        if warnings:
            story.append(Spacer(1, 0.2*inch))
            story.append(Paragraph("Data Quality Notes", heading2_style))
            for w in warnings:
                story.append(Paragraph(f"⚠ {w}", warning_style))

        # Footer Disclaimer
        story.append(Spacer(1, 0.3*inch))
        story.append(Paragraph(
            "—\n"
            "This AI-generated summary is based on the uploaded laboratory report and is intended for educational purposes only. "
            "It should not replace professional medical advice, diagnosis, or treatment. "
            "If you have symptoms or concerns, please contact a qualified healthcare provider immediately. "
            f"\nGenerated by LabLens AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            disclaimer_style
        ))

        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()

        if output_path:
            with open(output_path, "wb") as f:
                f.write(pdf_bytes)

        return pdf_bytes
